import 'package:flutter/material.dart';

enum TileType {
  property,
  incometax,
  wealthtax,
  chance,
  start,
  jail,
  resthouse,
  club
}

class TileColors {
  static const List<Color> palette = [
    Color.fromARGB(255, 65, 16, 13),
    Color.fromARGB(255, 8, 54, 10),
    Color.fromARGB(255, 10, 40, 65),
    Color.fromARGB(255, 51, 11, 70),
  ];
}

class TileData {
  final String label;
  final TileType type;
  final Color color;
  final int price;
  final int rent;
  final int renthouse1;
  final int renthouse2;
  final int renthouse3;
  final int renthotel;
  final int bankmortrage;
  final String? image;

  TileData({
    required this.label,
    this.type = TileType.property,
    this.color = Colors.black,
    this.price = 0,
    this.rent = 0,
    this.renthouse1 = 0,
    this.renthouse2 = 0,
    this.renthouse3 = 0,
    this.renthotel = 0,
    this.bankmortrage = 0,
    this.image,
  });

  static TileData getTileByIndex(int index) {
    return tiles[index];
  }
}

final List<TileData> tiles = [
  // LFT COLUMN
  TileData(
    label: 'Start',
    type: TileType.start,
    image: 'assets/images/start.jpg',
  ),
  TileData(
    label: 'India',
    type: TileType.property,
    color: TileColors.palette[0],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Japan',
    type: TileType.property,
    color: TileColors.palette[1],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Spain',
    type: TileType.property,
    color: TileColors.palette[2],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Egypt',
    type: TileType.property,
    color: TileColors.palette[3],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'IncomeTax',
    type: TileType.incometax,
    image: 'assets/images/incometax.jpg',
  ),
  TileData(
    label: 'China',
    type: TileType.property,
    color: TileColors.palette[0],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Italy',
    type: TileType.property,
    color: TileColors.palette[1],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Nepal',
    type: TileType.property,
    color: TileColors.palette[2],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Korea',
    type: TileType.property,
    color: TileColors.palette[3],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  // TOP ROW
  TileData(
    label: 'RestHouse',
    type: TileType.resthouse,
    image: 'assets/images/resthouse.jpg',
  ),
  TileData(
    label: 'Brazil',
    type: TileType.property,
    color: TileColors.palette[0],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Chile',
    type: TileType.property,
    color: TileColors.palette[1],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Kenya',
    type: TileType.property,
    color: TileColors.palette[2],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Tokyo',
    type: TileType.property,
    color: TileColors.palette[3],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Chance',
    type: TileType.chance,
    image: 'assets/images/chance1.jpg',
  ),
  TileData(
    label: 'Venice',
    type: TileType.property,
    color: TileColors.palette[0],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Swede',
    type: TileType.property,
    color: TileColors.palette[1],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'UAE',
    type: TileType.property,
    color: TileColors.palette[2],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Oman',
    type: TileType.property,
    color: TileColors.palette[3],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  // RIGHT COLUMN
  TileData(
    label: 'Jail',
    type: TileType.jail,
    image: 'assets/images/jail.jpg',
  ),
  TileData(
    label: 'Qatar',
    type: TileType.property,
    color: TileColors.palette[0],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Poland',
    type: TileType.property,
    color: TileColors.palette[1],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Czech',
    type: TileType.property,
    color: TileColors.palette[2],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Peru',
    type: TileType.property,
    color: TileColors.palette[3],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Chance',
    type: TileType.chance,
    image: 'assets/images/chance2.jpg',
  ),
  TileData(
    label: 'Ethiop',
    type: TileType.property,
    color: TileColors.palette[0],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Iceland',
    type: TileType.property,
    color: TileColors.palette[1],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Malta',
    type: TileType.property,
    color: TileColors.palette[2],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Congo',
    type: TileType.property,
    color: TileColors.palette[3],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  // BOTTOM ROW
  TileData(
    label: 'Club',
    type: TileType.club,
    image: 'assets/images/club.jpg',
  ),
  TileData(
    label: 'Samoa',
    type: TileType.property,
    color: TileColors.palette[0],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Fiji',
    type: TileType.property,
    color: TileColors.palette[1],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'US',
    type: TileType.property,
    color: TileColors.palette[2],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Sudan',
    type: TileType.property,
    color: TileColors.palette[3],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'WealthTax',
    type: TileType.wealthtax,
    image: 'assets/images/wealthtax.jpg',
  ),
  TileData(
    label: 'Yemen',
    type: TileType.property,
    color: TileColors.palette[0],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Cuba',
    type: TileType.property,
    color: TileColors.palette[1],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Iran',
    type: TileType.property,
    color: TileColors.palette[2],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
  TileData(
    label: 'Iraq',
    type: TileType.property,
    color: TileColors.palette[3],
    price: 1000,
    rent: 100,
    renthouse1: 100,
    renthouse2: 100,
    renthouse3: 100,
    renthotel: 100,
    bankmortrage: 100,
  ),
];
